# PoCX Miner Configuration

# network
chains:                               
  - name: 'PoCX Testnet'
    base_url: 'http://127.0.0.1:8081/'
    api_path: 'pocx'  # PoCX JSON-RPC 2.0 endpoint
    # auth_token: 'your-bearer-token-here'  # Optional bearer token for authentication
    block_time_seconds: 120  # Block time for network capacity calculation (default: 120s = 2 minutes)
    # target_quality: 1000000  # Optional: Only submit if quality < this, default: unlimited
    
    # Optional: Custom headers (advanced usage)
    # headers:
    #   'X-Custom-Header': 'your-value-here'
    
    # Optional: Per-account overrides (advanced usage)  
    # accounts:
    #   - account: 'your-account-address-here'
    #     target_quality: 500000  # Account-specific quality limit
    #     headers:
    #       'X-Account-Specific': 'value'

get_mining_info_interval: 1000        # default 1000ms
timeout: 5000                         # default 5000ms

# hdd 
plot_dirs: 
  - '/tmp/plots'

hdd_use_direct_io: true               # default true
hdd_wakeup_after: 30                  # default 30s
hdd_read_cache_in_warps: 16           # default: 16 warps

# mining
enable_on_the_fly_compression: true   # default true

# cpu 
cpu_threads: 0                        # default 0 (=auto: number of logical cpu cores)
cpu_thread_pinning: true              # default true

# logging
show_progress: true                   # default true  
 
benchmark: 'disabled'                 # default disabled, options (disabled, I/O, CPU)

console_log_level: 'info'             # default Info, options (off, error, warn, info, debug, trace)
logfile_log_level: 'warn'             # default Warn, options (off, error, warn, info, debug, trace)
logfile_max_count: 10                 # maximum number of log files to keep
logfile_max_size : 20                 # maximum size per logfile in MiB

# Low noise log patterns
console_log_pattern: "{({d(%H:%M:%S)} [{l}]):16.16} {m}{n}"
logfile_log_pattern: "{({d(%Y-%m-%d %H:%M:%S)} [{l}]):26.26} {m}{n}"
